name: Checks
on: [push]

jobs:
  test_lints:
    name: Test and Lint
    runs-on: ubuntu-22.04  # Updated to ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Fixed 'passwords' to 'password'
      - name: Checkout
        uses: actions/checkout@v3  # Updated to latest version
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
